### PR TITLE
Unbucketed levelized priority queue

### LINKED ISSUE #149: To bucket or not to bucket
Currently we always use a single bucket for the _levelized priority queue_. Experimentally this does provide a performance increase of 25% or more for reasonably large instances. Yet, this idea should not work well in practice, if the levels are very narrow. In that case, it would work better with a normal priority queue.

In #98 , #168 , #165 we derive estimates on the maximal size of the priority queue. This is also an upper bound on the size of each sorter in the levelized priority queue. If this estimate falls below some specific ε value, then we should use a non-bucketed version instead.

- [x] Implement a *non-bucketed* levelized priority queue as a separate template class. This one should have a similar public interface to the bucketed version we currently provide.

   This also needs to be thoroughly unit tested to have similar behaviour to the bucketed one.

The question is: what value of ε should be used?

- Some experiments are needed to figure out what value of ε should be used, but I imagine between 10 and 100 is a good place to start. One may be able  to look at the _Queens_ and _Knight's Tour_ examples in this repository, but I think the most usable results would be the _Picotrav_ benchmark [here](https://github.com/SSoelvsten/bdd-benchmark); just change the branch _Adiar_ in the _external/adiar_ folder.
- An even better value is probably by basing (also) on the number of elements that fits into a few cache-lines (64 bytes each). That is, whether on average, it is so small that everything fits into one or two cache lines.

Another question is: can we not do better than just reusing the above bounds? Can we weigh that value against one or more of the following?

- [ ] **Average level size**
  We can compute the *average* elements per level based on the given *max_size*. If we have more than one BDD, then we take the maximum number of levels (i.e. assuming the worst-case and average-case of as much overlap as possible)
- [ ] **Use max bucket size**
   We can have an upper bound on the number of elements of each level precomputed based on 1-level cuts. This is a better value to pick than the given *max size* that is based on 2-level cuts and the input size.

### LINKED ISSUE #363: Unsound upper bound in Intercut
**Describe the bug**
The upper bound for the `zdd_complement` function is not sound. The unit test

> *it adds out-of-set chain above root on { { 3 } } and U = { 0, 1, 2, 3 }*

breaks due to too small a priority queue. An ASCII drawing of this case is as follows
```
                      *   ---- x0
                     / \
                    *   *   ---- x1
        =>         / \ //
                  *   *   ---- x2
                 / \ //
   1            1   * ---- x3
  / \          / \  ||
  F T          T F  T
```
The computation currently looks as follows:
```cpp
  template<typename intercut_policy>
  size_t __intercut_2level_upper_bound(const typename intercut_policy::reduced_t &dd)
  {
    const cut_type ct = cut_type_with(intercut_policy::cut_false_sink,
                                      intercut_policy::cut_true_sink);
    const safe_size_t max_2level_cut = dd.max_2level_cut(ct);

    return to_size((2u * max_2level_cut) + 2u);
  }
```

**To Reproduce**
Run the unit tests on #347 (possibly the local version on @AnnaBlume99 's machine).

### PR DESCRIPTION
**Pull request by AnnaBlume99**
Closes #149 and also closes #363

### CODE REVIEW

File: src/adiar/internal/pred.h [hunk 1]
```diff
@@ -225,18 +227,26 @@ namespace adiar
...
     const size_t pq_1_memory_fits =
-      comparison_priority_queue_1_t<internal_sorter, internal_priority_queue>::memory_fits(pq_1_internal_memory);
+      comparison_priority_queue_1_t<ADIAR_LPQ_LOOKAHEAD, internal_sorter, internal_priority_queue>::memory_fits(pq_1_internal_memory);
 
     const size_t pq_2_memory_fits =
       comparison_priority_queue_2_t<internal_priority_queue>::memory_fits(pq_2_internal_memory);
 
     // TODO: Only one element per node in pq_2, so maximum is width (or their product)!
-    if(max_pq1_size <= pq_1_memory_fits && max_pq2_size <= pq_2_memory_fits) {
+    if(max_pq1_size <= no_lookahead_bound(2)) {
```
Comment (SSoelvsten) [inline src/adiar/internal/pred.h:236]: This `2` should be given by the policy. If it is the policy used for equality checking, then the *1* lookahead bound is more correct.

File: src/adiar/statistics.cpp [hunk 2]
```diff
@@ -126,9 +126,12 @@ namespace adiar
...
 
-    const uintwide_t total_lpqs = stats.lpq.internal + stats.lpq.external;
+    const uintwide_t total_lpqs = stats.lpq.unbucketed + stats.lpq.internal + stats.lpq.external;
 
     indent_level++;
+    o << indent << label << "unbucketed internal memory"
+      << stats.lpq.internal << " = " << percent_frac(stats.lpq.unbucketed, total_lpqs) << percent << endl;
+
     o << indent << label << "internal memory"
       << stats.lpq.internal << " = " << percent_frac(stats.lpq.internal, total_lpqs) << percent << endl;
```
Comment (SSoelvsten) [inline src/adiar/statistics.cpp:136]: When printing statistics, it would be better to know:
1. How much was in internal memory (`stats.lpq.unbucketed + stats.lpq.internal` out of `total_lpqs`)?
2. How much was the internal runs without buckets (`stats.lpq.unbucketed` out of `stats.lpq.unbucketed + stats.lpq.internal`)?

File: src/adiar/internal/levelized_priority_queue.h [hunk 3]
```diff
@@ -37,6 +37,12 @@ namespace adiar {
     typedef label_stream<> stream_t;
   };
 
+  constexpr size_t no_lookahead_bound(const size_t degree = 1)
+  {
+    size_t result = 8 * std::pow(2, degree);
+    return result;
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:43]: separate `return` is not really needed.

File: src/adiar/internal/levelized_priority_queue.h [hunk 4]
```diff
@@ -177,16 +183,17 @@ namespace adiar {
   /// \param LOOK_AHEAD   The number of levels (ahead of the current)
   ///                     explicitly handle with a sorting algorithm
   //////////////////////////////////////////////////////////////////////////////
+
   template <typename elem_t,
             typename elem_level_t,
+            label_t  LOOK_AHEAD = ADIAR_LPQ_LOOKAHEAD,
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:189]: I'd either place it as the very first argument or after the `elem` arguments.

File: src/adiar/internal/levelized_priority_queue.h [hunk 5]
```diff
@@ -969,45 +976,432 @@ namespace adiar {
...
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief Total number of data structures in Levelized Priority Queue.
+    ////////////////////////////////////////////////////////////////////////////
+    static constexpr size_t DATA_STRUCTURES = priority_queue_t::DATA_STRUCTURES;
+
+  public:
+    static tpie::memory_size_type memory_usage(tpie::memory_size_type no_elements)
+    {
+      return internal_priority_queue<elem_t, elem_comp_t>::memory_usage(no_elements)
+        + label_merger<file_t, level_comp_t, FILES>::memory_usage();
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1007]: Remove `label_merger` memory usage, since it is not in here.

File: src/adiar/internal/levelized_priority_queue.h [hunk 6]
```diff
@@ -969,45 +976,432 @@ namespace adiar {
...
+
+      if (memory_bytes < const_memory_bytes) {
+        return 0u;
+      }
+
+      // HACK: the 'internal_priority_queue' can take (two) fewer elements than
+      // the 'internal_sorter'. So, this is a slight under-approximation of what
+      // we truly could do with this amount of memory.
+      return internal_priority_queue<elem_t, elem_comp_t>
+        ::memory_fits((memory_bytes - const_memory_bytes) / DATA_STRUCTURES);
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1022]: Since there are no sorters this hack is not necessary. Just return what the `internal_priority_queue` can fit.

File: src/adiar/internal/levelized_priority_queue.h [hunk 7]
```diff
@@ -969,45 +976,432 @@ namespace adiar {
...
+
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief Total memory given in constructor.
+    ////////////////////////////////////////////////////////////////////////////
+    const tpie::memory_size_type _memory_given;
+
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief Memory to be used for the priority queue.
+    ////////////////////////////////////////////////////////////////////////////
+    tpie::memory_size_type _memory_occupied_by_priority_queue;
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1054]: This was only necessary for the buckets memory computations. This should be possible to remove, since all memory is used by the priority queue.

File: src/adiar/internal/levelized_priority_queue.h [hunk 8]
```diff
@@ -969,45 +976,432 @@ namespace adiar {
...
+    ////////////////////////////////////////////////////////////////////////////
+    stats_t::levelized_priority_queue_t &_stats;
+#endif
+
+  private:
+    static tpie::memory_size_type m_priority_queue(tpie::memory_size_type memory_given)
+    {
+      const tpie::memory_size_type eight_MiB = 8 * 1024;
+
+      return std::max(eight_MiB, memory_given);
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1079]: `memory_given` should in pretty much all cases be larger than 8 MiB. There is no need to increase it. In fact, I should fix this to only be whenever the type of the priority queue is the *external* memory variant.

File: src/adiar/internal/levelized_priority_queue.h [hunk 9]
```diff
@@ -969,45 +976,432 @@ namespace adiar {
...
+    /// \brief  Computes final memory usage of internal data structures to then
+    ///         distribute the remaining memory when initialising the buckets.
+    ///
+    /// \remark Call this function at the end of the constructor after the
+    ///         level_merger has hooked into the input.
+    ////////////////////////////////////////////////////////////////////////////
+    void init()
+    {
+
+    }
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1133]: Remove?

File: src/adiar/internal/levelized_priority_queue.h [hunk 10]
```diff
@@ -969,45 +976,432 @@ namespace adiar {
...
+
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief Whether there are any more (possibly all empty) levels.
+    ////////////////////////////////////////////////////////////////////////////
+    bool has_next_level() /*const*/
+    {
+      label_t next_label_from_queue = elem_level_t::label_of(_priority_queue.top());
+      return (has_current_level() && level_cmp_lt(_current_level, next_label_from_queue))
+              || (!has_current_level() && !_priority_queue.empty());
+    }
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1181]: This would crash if `_priority_queue.empty()`?

File: src/adiar/internal/levelized_priority_queue.h [hunk 11]
```diff
@@ -969,45 +976,432 @@ namespace adiar {
...
+      label_t result = elem_level_t::label_of(_priority_queue.top());
+      return result;
+    }
+
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief Whether one can push elements.
+    ////////////////////////////////////////////////////////////////////////////
+    bool can_push() /*const*/
+    {
+      return has_next_level();
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1197]: Or just `return true`.

File: src/adiar/internal/levelized_priority_queue.h [hunk 12]
```diff
@@ -969,45 +976,432 @@ namespace adiar {
...
+      // Edge Case: ---------------------------------------------------------- :
+      //   The stop level is before the next level of the queue
+      label_t next_label_from_queue = elem_level_t::label_of(_priority_queue.top());
+      if(has_stop_level && level_cmp_le(stop_level, next_label_from_queue)) {
+        _current_level = stop_level;
+        return;
+      }
+
+      // Primary Case: ------------------------------------------------------- :
+      //   Set the level to be the next from the queue, and forward the level_merger
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1257]: Remove: "and forward the level_merger"

**Review by SSoelvsten — CHANGES_REQUESTED** [review]
Very good first draft! :slightly_smiling_face:

File: src/adiar/statistics.cpp [hunk 13]
```diff
@@ -126,9 +126,12 @@ namespace adiar
   {
     o << indent << bold_on << "levelized priority queue" << bold_off << endl;
 
-    const uintwide_t total_lpqs = stats.lpq.internal + stats.lpq.external;
+    const uintwide_t total_lpqs = stats.lpq.unbucketed + stats.lpq.internal + stats.lpq.external;
 
     indent_level++;
+    o << indent << label << "unbucketed internal memory"
+      << stats.lpq.internal << " = " << percent_frac(stats.lpq.unbucketed, total_lpqs) << percent << endl;
```
Comment (SSoelvsten) [inline src/adiar/statistics.cpp:133]: `stats.lpq.internal` is still printed here.

**Comment by SSoelvsten** [comment]
Here are a few statistics on how much the unbucketed priority queue was used in the Picotrav benchmark.

| arithmetic/adder | arithmetic/sin | random_control/cavlc | random_control/ctrl.blif |
|-----------------------|-------------------|------------------------------|--------------------------------|
| 88.9%                | 12.96%          | 90.65%                       | 99.64%                         |

With the Queens problem, we have

| 4           | 5            | 6    |
|------------|------------|------|
| 26.67% | 20.83% | 0% |

So best are *ctrl* and *cavlc* for testing the performance differenc. Possible, also look at *adder*.

**Comment by SSoelvsten** [comment]
Even for the *ctrl* benchmark we do only really see a ~3% performance increase .

File: src/adiar/internal/levelized_priority_queue.h (hunk 4 above)
Comment (AnnaBlume99) [reply src/adiar/internal/levelized_priority_queue.h:189]: This is not possible, because it needs to come after the arguments that have no default, but be the first default argument

File: src/adiar/internal/levelized_priority_queue.h [hunk 14]
```diff
@@ -37,6 +37,32 @@ namespace adiar {
...
+  constexpr size_t no_lookahead_bound(const size_t degree = 1)
+  {
+    return 8 * std::pow(2, degree);
+  }
+
+  ////////////////////////////////////////////////////////////////////////////
+  /// \brief Strictly less ' < ' between two levels.
+  ////////////////////////////////////////////////////////////////////////////
+  template<typename level_comp_t>
+  inline bool level_cmp_lt(const label_t l1, const label_t l2, level_comp_t level_comp)
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:52]: The `level_comp` should be a reference, such that it is not using the copy-constructor.

File: src/adiar/internal/levelized_priority_queue.h [hunk 15]
```diff
@@ -37,6 +37,32 @@ namespace adiar {
...
+  {
+    return level_comp(l1, l2);
+  }
+
+  ////////////////////////////////////////////////////////////////////////////
+  /// \brief Less or equal ' <= ' between two levels.
+  ////////////////////////////////////////////////////////////////////////////
+  template<typename level_comp_t>
+  inline bool level_cmp_le(const label_t l1, const label_t l2, level_comp_t level_comp)
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:61]: The `level_comp` should be a reference, such that it is not using the copy-constructor.

File: src/adiar/internal/levelized_priority_queue.h (hunk 4 above)
Comment (SSoelvsten) [reply src/adiar/internal/levelized_priority_queue.h:209]: Hmm, then I'd either (a) move it after `elem_comp_t` or make it a non-default argument.

File: src/adiar/internal/levelized_priority_queue.h [hunk 16]
```diff
@@ -969,48 +980,377 @@ namespace adiar {
...
+      adiar_debug(!has_current_level() || empty_level(),
+                  "Level is empty before moving on to the next");
+
+      const bool has_stop_level = stop_level != NO_LABEL;
+
+      adiar_debug(has_stop_level || !empty(),
+                  "Either a stop level is given or we have some non-empty level to forward to");
+
+      adiar_debug(has_next_level(),
+                  "There should be a next level to go to");
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1205]: Assuming the `!has_current_level() || empty_level()` is this not equivalent to `!empty`?

File: src/adiar/internal/levelized_priority_queue.h [hunk 17]
```diff
@@ -969,48 +980,377 @@ namespace adiar {
...
+      // Edge Case: ---------------------------------------------------------- :
+      //   The given stop_level is prior to the next level or there is nothing in the queue
+      if ((has_stop_level && level_cmp_lt<level_comp_t>(stop_level, next_level(), _level_comparator)) || _priority_queue.empty()) {
+        _current_level = stop_level;
+        return;
+      }
+
+      // Edge Case: ---------------------------------------------------------- :
+      //   The stop level is before the next level of the queue
+      label_t next_label_from_queue = elem_level_t::label_of(_priority_queue.top());
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1216]: given that `empty_level()` must be true, then this can be replaced with `next_level()`, I believe.

**Review by SSoelvsten — CHANGES_REQUESTED** [review]
Tiny nitpicks left.

File: src/adiar/internal/levelized_priority_queue.h (hunk 4 above)
Comment (SSoelvsten) [reply src/adiar/internal/levelized_priority_queue.h:209]: Hmm, then I'd either (a) move it after `elem_comp_t` or make it a non-defaulted argument.

Comment (AnnaBlume99) [reply src/adiar/internal/levelized_priority_queue.h:209]: It will be moved after elem_comp_t. We almost always use the standard lookahead and it seems odd to always have to specify this

File: src/adiar/internal/intercut.h [hunk 18]
```diff
@@ -345,29 +349,37 @@ namespace adiar
...
-    if(max_pq_size <= pq_1_memory_fits && max_pq_size <= pq_2_memory_fits) {
+    /*if(max_pq_size <= no_lookahead_bound(1)) {
+#ifdef ADIAR_STATS
+      stats_intercut.lpq.unbucketed++;
+#endif
+      return __intercut<intercut_policy,
+                        intercut_priority_queue_1_t<0, internal_sorter, internal_priority_queue>,
+                        intercut_priority_queue_2_t<0, internal_sorter, internal_priority_queue>>
+        (dd, labels, pq_1_internal_memory, pq_2_internal_memory, max_pq_size);
+    } else*/ if(max_pq_size <= pq_1_memory_fits && max_pq_size <= pq_2_memory_fits) {
```
Comment (SSoelvsten) [inline src/adiar/internal/intercut.h:376]: If #362 is merged first, then when rebasing on-top have this uncommented again.

File: src/adiar/internal/levelized_priority_queue.h [hunk 19]
```diff
@@ -967,50 +978,379 @@ namespace adiar {
...
+
+  public:
+    static tpie::memory_size_type memory_usage(tpie::memory_size_type no_elements)
+    {
+      return internal_priority_queue<elem_t, elem_comp_t>::memory_usage(no_elements);
+    }
+
+    static tpie::memory_size_type memory_fits(tpie::memory_size_type memory_bytes)
+    {
+      return internal_priority_queue<elem_t, elem_comp_t>::memory_fits(memory_bytes / DATA_STRUCTURES);
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1017]: I believe the `/ DATA_STRUCTURES` semantically makes little sense (it works of course, because *DATA_STRUCTURES* is equals to 1): should the `memory_fits` of the internal_priority_queue not be able to deal with the number of data structures within itself?

File: src/adiar/internal/levelized_priority_queue.h [hunk 20]
```diff
@@ -967,50 +978,379 @@ namespace adiar {
...
+      adiar_debug(has_current_level(),
+                  "Needs to have a 'current' level to read the level from");
+
+      return _current_level;
+    }
+
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief Whether there are any more (possibly all empty) levels.
+    ////////////////////////////////////////////////////////////////////////////
+    bool has_next_level() /*const*/
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1145]: This probably can be made `const`, given that the `.empty()` and the `.top()` functions can be *const*?

File: src/adiar/internal/levelized_priority_queue.h [hunk 21]
```diff
@@ -967,50 +978,379 @@ namespace adiar {
...
+      }
+      label_t next_label_from_queue = elem_level_t::label_of(_priority_queue.top());
+      return (has_current_level() && level_cmp_lt<level_comp_t>(_current_level, next_label_from_queue, _level_comparator))
+              || (!has_current_level() && !_priority_queue.empty());
+    }
+
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief The label of the next (possibly empty) level.
+    ////////////////////////////////////////////////////////////////////////////
+    label_t next_level() /*const*/
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1158]: I believe, this can be made `const`?

File: src/adiar/internal/levelized_priority_queue.h [hunk 22]
```diff
@@ -967,50 +978,379 @@ namespace adiar {
...
+    {
+      label_t result = elem_level_t::label_of(_priority_queue.top());
+      return result;
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1161]: Maybe turn this into a one-liner?

File: src/adiar/internal/levelized_priority_queue.h [hunk 23]
```diff
@@ -967,50 +978,379 @@ namespace adiar {
...
+    }
+
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief Whether one can push elements.
+    ////////////////////////////////////////////////////////////////////////////
+    bool can_push() /*const*/
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1167]: Definitely `const`

File: src/adiar/internal/levelized_priority_queue.h [hunk 24]
```diff
@@ -967,50 +978,379 @@ namespace adiar {
...
+      // Primary Case: ------------------------------------------------------- :
+      //   Set the level to be the next from the queue
+      _current_level = next_level_from_queue;
+    }
+
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief Whether the current level is empty. Is false, if there is no
+    ///       'current' level.
+    ////////////////////////////////////////////////////////////////////////////
+    bool empty_level()
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1231]: Could this be `const`?

File: src/adiar/internal/levelized_priority_queue.h [hunk 25]
```diff
@@ -967,50 +978,379 @@ namespace adiar {
...
+             _priority_queue.empty() ||
+             current_level() != elem_level_t::label_of(_priority_queue.top());
+    }
+
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief Whether any elements can be pulled (from the current level).
+    ///
+    /// \sa    levelized_priority_queue::empty_level
+    ////////////////////////////////////////////////////////////////////////////
+    bool can_pull()
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1244]: If `.empty_level()` can be made `const` then this one too.

File: src/adiar/internal/levelized_priority_queue.h [hunk 26]
```diff
@@ -967,50 +978,379 @@ namespace adiar {
...
+    {
+      return !empty_level();
+    }
+
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief Obtain the top element of the current level.
+    ////////////////////////////////////////////////////////////////////////////
+    elem_t top()
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1252]: Can be made `const`.

File: src/adiar/internal/levelized_priority_queue.h [hunk 27]
```diff
@@ -967,50 +978,379 @@ namespace adiar {
...
+      adiar_debug (can_pull(), "Can only obtain top element on non-empty level");
+      return _priority_queue.top();
+    }
+
+    ////////////////////////////////////////////////////////////////////////////
+    /// \brief Obtain the top element of the current level.
+    ///
+    /// \sa    levelized_priority_queue::top
+    ////////////////////////////////////////////////////////////////////////////
+    elem_t peek()
```
Comment (SSoelvsten) [inline src/adiar/internal/levelized_priority_queue.h:1263]: Can be made `const`.

File: test/adiar/internal/test_levelized_priority_queue.cpp [hunk 28]
```diff
@@ -2455,186 +2455,2168 @@ go_bandit([]() {
...
+          pq.push(pq_test_data {3, 1});
+
+          AssertThat(pq.has_current_level(), Is().False());
+
+          AssertThat(pq.has_current_level(), Is().False());
+          AssertThat(pq.has_next_level(), Is().True());
+          AssertThat(pq.next_level(), Is().EqualTo(3u));
+
+          pq.setup_next_level(2u);
+        });
```
Comment (SSoelvsten) [inline test/adiar/internal/test_levelized_priority_queue.cpp:2867]: Remove: this unit test is equivalent to *forwards to first level*

File: test/adiar/internal/test_levelized_priority_queue.cpp [hunk 29]
```diff
@@ -2455,186 +2455,2168 @@ go_bandit([]() {
...
+
+          AssertThat(pq.has_current_level(), Is().True());
+          AssertThat(pq.current_level(), Is().EqualTo(7u));
+
+          AssertThat(pq.empty_level(), Is().False());
+        });
+      });
+
+      describe(".setup_next_level(stop_label)", [&]() {
+        it("forwards to first level", [&]() {
```
Comment (SSoelvsten) [inline test/adiar/internal/test_levelized_priority_queue.cpp:2761]: Rename: *forwards to stop level [1]*

File: test/adiar/internal/test_levelized_priority_queue.cpp [hunk 30]
```diff
@@ -2455,186 +2455,2168 @@ go_bandit([]() {
...
+          AssertThat(pq.has_current_level(), Is().True());
+          AssertThat(pq.current_level(), Is().EqualTo(2u));
+
+          AssertThat(pq.empty_level(), Is().True());
+
+          AssertThat(pq.has_next_level(), Is().True());
+          AssertThat(pq.next_level(), Is().EqualTo(3u));
+        });
+
+        it("forwards to second level", [&]() {
```
Comment (SSoelvsten) [inline test/adiar/internal/test_levelized_priority_queue.cpp:2792]: Rename: *forwards to next level with content [1]*

File: test/adiar/internal/test_levelized_priority_queue.cpp [hunk 31]
```diff
@@ -2455,186 +2455,2168 @@ go_bandit([]() {
...
+
+          AssertThat(pq.has_current_level(), Is().False());
+          AssertThat(pq.has_next_level(), Is().True());
+          AssertThat(pq.next_level(), Is().EqualTo(3u));
+
+          pq.setup_next_level(3u);
+
+          AssertThat(pq.has_current_level(), Is().True());
+          AssertThat(pq.current_level(), Is().EqualTo(3u));
+        });
```
Comment (SSoelvsten) [inline test/adiar/internal/test_levelized_priority_queue.cpp:2844]: Remove: this is equivalent to *forwards to second level*

File: test/adiar/internal/test_levelized_priority_queue.cpp [hunk 32]
```diff
@@ -2455,186 +2455,2168 @@ go_bandit([]() {
...
+          pq.setup_next_level(3u);
+
+          AssertThat(pq.has_current_level(), Is().True());
+          AssertThat(pq.current_level(), Is().EqualTo(3u));
+
+          AssertThat(pq.has_next_level(), Is().True());
+          AssertThat(pq.next_level(), Is().EqualTo(4u));
+        });
+
+        it("forwards to stop level", [&]() {
```
Comment (SSoelvsten) [inline test/adiar/internal/test_levelized_priority_queue.cpp:2924]: Rename: *forwards to stop level [2]*

File: test/adiar/internal/test_levelized_priority_queue.cpp [hunk 33]
```diff
@@ -2455,186 +2455,2168 @@ go_bandit([]() {
...
+          AssertThat(pq.has_next_level(), Is().True());
+          AssertThat(pq.next_level(), Is().EqualTo(2u));
+
+          pq.setup_next_level(3u);
+
+          AssertThat(pq.has_current_level(), Is().True());
+          AssertThat(pq.current_level(), Is().EqualTo(2u));
+        });
+
+        it("forwards to first level for unknown level prior to second level", [&]() {
```
Comment (SSoelvsten) [inline test/adiar/internal/test_levelized_priority_queue.cpp:2895]: Rename: *forwards to unknown level without content [1]*

File: test/adiar/internal/test_levelized_priority_queue.cpp [hunk 34]
```diff
@@ -2455,186 +2455,2168 @@ go_bandit([]() {
...
+
+          pq.setup_next_level(6u);
+
+          AssertThat(pq.has_current_level(), Is().True());
+          AssertThat(pq.current_level(), Is().EqualTo(4u));
+
+          AssertThat(pq.empty_level(), Is().False());
+        });
+
+        it("forwards past unknown level", [&]() {
```
Comment (SSoelvsten) [inline test/adiar/internal/test_levelized_priority_queue.cpp:2984]: Rename: *forwards to unknown level without content [2]*

File: test/adiar/internal/test_levelized_priority_queue.cpp [hunk 35]
```diff
@@ -2455,186 +2455,2168 @@ go_bandit([]() {
...
+          pq.setup_next_level();
+
+          AssertThat(pq.can_pull(), Is().True());
+          AssertThat(pq.pull(), Is().EqualTo(pq_test_data {4, 1}));
+
+          pq.push(pq_test_data {5, 1});
+
+          AssertThat(pq.can_pull(), Is().False());
+
+          pq.setup_next_level(); // read: 5
```
Comment (SSoelvsten) [inline test/adiar/internal/test_levelized_priority_queue.cpp:3216]: `// 5`

**Review by SSoelvsten — CHANGES_REQUESTED** [review]
A few more nitpicks.

- There are quite a few functions that can be made `const`, I believe.
- I looked through the unit tests and found a few things to tidy up. Also, they seem to be out-of-order. Is that just the order they were in initially or can they be sorted?

File: src/adiar/internal/levelized_priority_queue.h (hunk 20 above)
Comment (AnnaBlume99) [reply src/adiar/internal/levelized_priority_queue.h:1145]: No unfortunately. Something with the label_of() function prevents it from being const

File: src/adiar/internal/levelized_priority_queue.h (hunk 21 above)
Comment (AnnaBlume99) [reply src/adiar/internal/levelized_priority_queue.h:1158]: Same as for has_next_level()

File: src/adiar/internal/levelized_priority_queue.h (hunk 24 above)
Comment (AnnaBlume99) [reply src/adiar/internal/levelized_priority_queue.h:1231]: Same as for has_next_level()

File: src/adiar/internal/levelized_priority_queue.h (hunk 26 above)
Comment (AnnaBlume99) [reply src/adiar/internal/levelized_priority_queue.h:1252]: No because the debug statement uses can_pull() which uses empty()

File: src/adiar/internal/levelized_priority_queue.h (hunk 27 above)
Comment (AnnaBlume99) [reply src/adiar/internal/levelized_priority_queue.h:1263]: Cannot be made const because top() cannot

File: src/adiar/internal/levelized_priority_queue.h (hunk 25 above)
Comment (AnnaBlume99) [reply src/adiar/internal/levelized_priority_queue.h:1244]: Same as for has_next_level()

File: src/adiar/internal/intercut.h [hunk 36]
```diff
@@ -281,9 +281,9 @@ namespace adiar
   {
     const cut_type ct = cut_type_with(intercut_policy::cut_false_sink,
                                       intercut_policy::cut_true_sink);
-    const safe_size_t max_2level_cut = dd.max_2level_cut(ct);
+    const safe_size_t max_1level_cut = dd.max_1level_cut(ct);
 
-    return to_size((2u * max_2level_cut) + 2u);
+    return to_size(3 * ((intercut_policy::mult_factor * max_1level_cut) + 2u) / 2);
```
Comment (SSoelvsten) [inline src/adiar/internal/intercut.h:286]: The +2 should be outside of the 3/2 .

File: src/adiar/internal/intercut.h [hunk 37]
```diff
@@ -333,16 +333,20 @@ namespace adiar
...
       return __intercut<intercut_policy,
                         intercut_priority_queue_1_t<0, internal_sorter, internal_priority_queue>,
                         intercut_priority_queue_2_t<0, internal_sorter, internal_priority_queue>>
         (dd, labels, pq_1_internal_memory, pq_2_internal_memory, max_pq_size);
+<<<<<<< HEAD
     } else if(max_pq_size <= pq_1_memory_fits && max_pq_size <= pq_2_memory_fits) {
 >>>>>>> a6f4a4d (Make algorithms use the new LPQ when input is small)
+=======
+    } else*/ if(max_pq_size <= pq_1_memory_fits && max_pq_size <= pq_2_memory_fits) {
+>>>>>>> 6dffa4d (Remove _level_merger)
```
Comment (SSoelvsten) [inline src/adiar/internal/intercut.h]: Lingering merge conflict inside of a commit

File: src/adiar/internal/intercut.h [hunk 38]
```diff
@@ -306,27 +308,68 @@ namespace adiar
...
+    if(max_pq_size <= no_lookahead_bound(1)) {
+#ifdef ADIAR_STATS
+      stats_intercut.lpq.unbucketed++;
+#endif
+      return __intercut<intercut_policy,
+                        intercut_priority_queue_1_t<0, internal_sorter, internal_priority_queue>,
+                        intercut_priority_queue_2_t<0, internal_sorter, internal_priority_queue>>
+        (dd, labels, pq_1_internal_memory, pq_2_internal_memory, max_pq_size);
+    } else if(max_pq_size <= pq_1_memory_fits && max_pq_size <= pq_2_memory_fits) {
+>>>>>>> a6f4a4d (Make algorithms use the new LPQ when input is small)
```
Comment (SSoelvsten) [inline src/adiar/internal/intercut.h]: Lingering merge conflict!

File: src/adiar/internal/intercut.h [hunk 39]
```diff
@@ -306,27 +308,68 @@ namespace adiar
...
 #endif
       return __intercut<intercut_policy,
+<<<<<<< HEAD
                         intercut_priority_queue_t<internal_sorter, internal_priority_queue>>
         (dd, labels, pq_internal_memory, max_pq_size);
+=======
+                        intercut_priority_queue_1_t<ADIAR_LPQ_LOOKAHEAD, internal_sorter, internal_priority_queue>,
+                        intercut_priority_queue_2_t<ADIAR_LPQ_LOOKAHEAD, internal_sorter, internal_priority_queue>>
+        (dd, labels, pq_1_internal_memory, pq_2_internal_memory, max_pq_size);
+>>>>>>> a6f4a4d (Make algorithms use the new LPQ when input is small)
```
Comment (SSoelvsten) [inline src/adiar/internal/intercut.h]: Lingering merge conflict

File: src/adiar/internal/intercut.h [hunk 40]
```diff
@@ -306,27 +308,68 @@ namespace adiar
...
 
       return __intercut<intercut_policy,
+<<<<<<< HEAD
                         intercut_priority_queue_t<external_sorter, external_priority_queue>>
         (dd, labels, pq_memory, max_pq_size);
+=======
+                        intercut_priority_queue_1_t<ADIAR_LPQ_LOOKAHEAD, external_sorter, external_priority_queue>,
+                        intercut_priority_queue_2_t<ADIAR_LPQ_LOOKAHEAD, external_sorter, external_priority_queue>>
+        (dd, labels, pq_1_memory, pq_2_memory, max_pq_size);
+>>>>>>> a6f4a4d (Make algorithms use the new LPQ when input is small)
```
Comment (SSoelvsten) [inline src/adiar/internal/intercut.h]: Lingering merge conflict!

**Review by SSoelvsten — CHANGES_REQUESTED** [review]
Quite a lot got messed up when rebasing on *main*.

- [ ] There are merge conflicts in *internal/intercut.h* in commit 2404130b717055ef80bada8578ee8956598ef32c
- [ ] Commit cb38e8a73d2d06553d3f9043f8c01b8afdb5e792 includes changes to *test_levelized_priority_queue* that have nothing to do with fixing the intercut size bound.

Furthermore, there is a tiny problem with the *+2* in the intercut size bound.

**Review by SSoelvsten — APPROVED** [review]

**Review by SSoelvsten — APPROVED** [review]
