### PR TITLE
Make sure size_bound computations do not overflow and cause wrong choice of auxilliary data structures

### LINKED ISSUE #262: Safe over-approximations from overflowing
All our bounds derived in #98 and #165 may overflow. That is, we can by accident use internal memory, even if there is not enough space for it. Other later ideas may also break due to an overflow.

But, note the following about two numbers with *n* and *m* bits

- **addition**: Uses at most *max(n,m)+1* bits
- **multiplication**: Uses at most *m + n* bits

The number of bits can be derived in two ways.

1. The fastest way we can resolve this is to reverse the above to provide an upper bound on all input sizes we care about. That is, for the product construction, where we have **2** numbers multiplied together, we should at most use *64 / **2** - 1* bits, i.e. we can check whether all inputs are smaller than the `constexpr` `1 << (64 / 2 - 1)`.

   For the product construction and quantification this seems fine. Yet, the If-Then-Else is only *64 / **3** - 1* bits each, which are only a few hundred megabytes.
2. For more precision, we actually need to know the number of bits for each input number. The following piece of code finds the exact number of bits used for an unsigned integer. This takes at most O(64) operations to compute.
   ```cpp
   unsigned bits, var = (x < 0) ? -x : x;
   for(bits = 0; var != 0; ++bits) var >>= 1;
   ```
   This can be added as an inline function `number_of_bits` in *adiar/internal/util.h*. Then we can approximate the number of bits needed to compute the final result.

So, we can safe-guard every operation in the bounds computations. If it may overflow, then these functions return `std::numeric_limits<size_t>::max()` instead.

Specifically, this only applies to the product constructions, where we cannot just use a simple input number (which definitely does not overflow).

- [ ] *bdd/if_then_else.cpp*
- [ ] *internal/intercut.h*
- [ ] *internal/product_construction.h*
- [ ] *internal/quantify.h*

### PR DESCRIPTION
**Pull request by AnnaBlume99**
Closes #262

### CODE REVIEW

File: src/adiar/zdd/pred.cpp [hunk 1]
```diff
@@ -17,7 +17,15 @@ namespace adiar {
...
-      return in_1.size() * in_2.size();
+      // Can the size_bound computation overflow?
+      const size_t max_bits = max_bits_for_mult(number_of_bits(in_1.size()),
+                                                number_of_bits(in_2.size()));
+
+      if(max_bits <= 64) {
+        return in_1.size() * in_2.size();
+      } else {
+        return std::numeric_limits<size_t>::max();
+    }
```
Comment (SSoelvsten) [inline src/adiar/zdd/pred.cpp:28]: Misindentation.

File: src/adiar/internal/quantify.h [hunk 2]
```diff
@@ -274,7 +274,15 @@ namespace adiar
   template<typename quantify_policy>
   size_t __quantify_size_based_upper_bound(const typename quantify_policy::reduced_t &in)
   {
-    return (in.file.size()) * (in.file.size()) + 2;
+    // Can the size_bound computation overflow?
+    const size_t mult_bits = max_bits_for_mult(number_of_bits(in.file.size()), 2u);
```
Comment (SSoelvsten) [inline src/adiar/internal/quantify.h:278]: The right-hand side should be the file size once more, not `2u`.

**Review by SSoelvsten — CHANGES_REQUESTED** [review]

File: src/adiar/internal/quantify.h (hunk 2 above)
Comment (SSoelvsten) [reply src/adiar/internal/quantify.h:278]: If you want to make it fast, then this is the same as the twice the number of bits for the `in.file.size()`, i.e. you can do it with a simple left-shift.

File: src/adiar/internal/util.h [hunk 3]
```diff
@@ -50,6 +50,73 @@ namespace adiar
     return vars;
   }
 
+  inline size_t number_of_bits(size_t x)
+  {
+    unsigned bits, var = x;
+    for(bits = 0; var != 0; ++bits) var >>= 1;
+    return bits;
+  }
```
Comment (SSoelvsten) [inline src/adiar/internal/util.h:58]: This can be made into a `private static` function in `bits_approximation`.

File: src/adiar/internal/util.h [hunk 4]
```diff
@@ -50,6 +50,73 @@ namespace adiar
...
+    bits_approximation operator* (const bits_approximation other) const
+    {
+      return approximate_multiplication(bits, other.bits);
+    }
+
+    bits_approximation operator* (const size_t other) const
+    {
+      return approximate_multiplication(bits, other);
+    }
+  };
```
Comment (SSoelvsten) [inline src/adiar/internal/util.h:119]: I would argue, that you should remove this, since we are intending the operators to reflect the semantics of upper bounding the number of bits, while here we treat the value of `other` as the number of its bits.

File: src/adiar/internal/util.h (hunk 3 above)
Comment (SSoelvsten) [reply src/adiar/internal/util.h:58]: Also, you may rename this into `log2` since that technically what we are computing.

File: src/adiar/internal/util.h [hunk 5]
```diff
@@ -50,6 +50,73 @@ namespace adiar
...
+    ////////////////////////////////////////////////////////////////////////////
+    /// An over-approximation of the number of bits to represent a number
+    ////////////////////////////////////////////////////////////////////////////
+    bits_approximation(const size_t size)
+      : bits_approximation(size, false)
+    { }
+
+  private:
+    bits_approximation(const size_t size, const bool size_in_bits)
+      : bits(size_in_bits ? size : number_of_bits(size))
```
Comment (SSoelvsten) [inline src/adiar/internal/util.h:75]: About the boolean `size_in_bits`
- It should probably be renamed to `size_is_in_bits` or `skip_log2`. Alternatively, it could be renamed to `is_number_of_bits` or `compute_log2` and then invert the ternary.
- You can make it `constexpr` to shortcut the ternary at compile-time.

At present time, I have no better idea than using a boolean like this. 🤷

**Review by SSoelvsten — CHANGES_REQUESTED** [review]

**Review by SSoelvsten — APPROVED** [review]
